### PR TITLE
Changed the black theme to soft black

### PR DESCRIPTION
**Pull request by AshutoshDash1999**
Algoders-community

### CODE REVIEW

**Comment by mohityadav0903** [comment]
hey @AshutoshDash1999 it's looking too dusty . can u make it little bit shiny. And also change colors of few more thing so that your PR can look valid

**Comment by mohityadav0903** [comment]
Ok it'll be good if you can show me first

**Comment by AshutoshDash1999** [comment]
Hey, sorry to bother but i wanted to know the reason for closing this issue.

**Comment by mohityadav0903** [comment]
Hey @AshutoshDash1999 I haven't closed the issue.
It's still opened. I have mentioned the theme and design if you want to contribute to that, you can create a new PR

**Pull request closed without merging**
