### PR TITLE
Theme changed

### PR DESCRIPTION
**Pull request by YalfamIamShaon**
I have changed the theme.

### CODE REVIEW

**Comment by mohityadav0903** [comment]
@YalfamIamShaon plz solve the conflicts

**Comment by mohityadav0903** [comment]
hey @YalfamIamShaon it has so many syntex errors, solve them and then raise a PR

**Comment by mohityadav0903** [comment]
hey @YalfamIamShaon check ur PR it has so many errors in syntex solve them asap our build is failing

**Comment by YalfamIamShaon** [comment]
Sorry @mohityadav0903 . I've found those errors, Let me solve it..

**Pull request merged**
