### PR TITLE
Added fade in effect on about us page when scroll down

### PR DESCRIPTION
**Pull request by nitishsaini706**
i wanted to first apply the scrolling effect on a component , so added fade in effect on about us page and also on the main banner image in home section

### CODE REVIEW

**Comment by mohityadav0903** [comment]
Hey @nitishsaini706  can u add another effects other than fade in fade out on all other components

**Comment by nitishsaini706** [comment]
yaa sure , But I think this will take time as some components were not responding on adding effects

**Comment by mohityadav0903** [comment]
hey can u pull the code first and then make a pr

**Comment by nitishsaini706** [comment]
> hey can u pull the code first and then make a pr

Already did

**Pull request merged**
