### PR TITLE
Enhancement of Navbar

### LINKED ISSUE #1: Make navbar stylish
remove hover text underline

### PR DESCRIPTION
**Pull request by HarshKumarChoudary**
# Fixes #1
This PR updates the Navbar as suggested in the issue section.
The following fixes has been done.

- Added logo to navbar.
- Moved the title to the left side of navbar
- moved buttons to right side.
- added hover effect to buttons.

image

Note : in image login button is blue due to mouse hovered over it.

### CODE REVIEW

**Comment by mohityadav0903** [comment]
image
hey @HarshKumarChoudary can u change it to look like this

**Comment by HarshKumarChoudary** [comment]
Yes I will do that, Due to my exams going on I will complete it by day after tomorrow.

**Comment by mohityadav0903** [comment]
hey @HarshKumarChoudary can u do it by tomorrow

**Comment by HarshKumarChoudary** [comment]
ok I will do it by tomorrow.

**Comment by HarshKumarChoudary** [comment]
This branch was having conflicts so I created another PR #45 solving issue#1. Please review that. thanks.

**Pull request closed without merging**
