### PR TITLE
Implement Hyperlinks on Footer and Header

### PR DESCRIPTION
**Pull request by Shubham29012001**
#58

## Proposed Changes
- Implemented Hyperlinks on Footer
- Implemented Scroll Effect on Topbar
- Add a Separate Page link in the Homepage Component

## Checklist

- [x] ✅ My code follows the code style of this project.
- [ ] 📝 My change requires a change to the documentation.
- [ ] 🎀 I have updated the documentation accordingly.
- [x] 👀 I have read the [**CONTRIBUTING**](https://github.com/mohityadav0903/Algoders-Community/blob/main/contribution.md) document.
- [x] 🌟 ed the repo

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Output Screenshots
image

### CODE REVIEW

**Comment by Shubham29012001** [comment]
Hey @mohityadav0903, have a look at this PR? It won't take much time.

**Comment by mohityadav0903** [comment]
hey @Shubham29012001 i want u to smooth scroll to the home page after clicking any nav item.

**Comment by Shubham29012001** [comment]
Hey @mohityadav0903, I have implemented the things you asked for on the nav items. Do have a look.

**Review by mohityadav0903 — APPROVED** [review]

**Comment by Shubham29012001** [comment]
Hey @mohityadav0903, can you please add the proper GSSoC Label with level to the issue as well as on the Merged PR?

**Pull request merged**
